import type { AcademicQueryable } from './schema';

/**
 * Read pillar — starter content.
 *
 * Attaches real lesson notes to existing curriculum topic IDs (see curriculum-seed.ts).
 * Seeding is per-row idempotent (`ON CONFLICT (id) DO NOTHING`) so new readings can be
 * appended later without disturbing a student's existing progress rows.
 */

type SeedReadingKind = 'lesson_note' | 'explainer' | 'reference' | 'past_paper' | 'glossary';

interface SeedReading {
  id: string;
  topicId: string;
  title: string;
  summary: string;
  body: string;
  kind: SeedReadingKind;
  readingMinutes: number;
  sortOrder: number;
}

const READING_DATA: SeedReading[] = [
  // ── PRIMARY — Standard 1 ──────────────────────────────────────────────
  {
    id: 'read-std1-math-1-counting',
    topicId: 'std1-math-1',
    title: 'Counting from 1 to 100',
    summary: 'How to count, read, and write whole numbers up to one hundred.',
    kind: 'lesson_note',
    readingMinutes: 5,
    sortOrder: 1,
    body: [
      '## What counting means',
      '',
      'Counting tells us **how many** things there are. When you count, you say one number for',
      'each thing, and you never skip or repeat a thing.',
      '',
      '## Counting to 10',
      '',
      '1, 2, 3, 4, 5, 6, 7, 8, 9, 10',
      '',
      'The last number you say is the answer. If you count five mangoes and the last number you',
      'say is five, there are five mangoes.',
      '',
      '## Tens and ones',
      '',
      'Numbers bigger than 9 are built from **tens** and **ones**.',
      '',
      '- 14 means 1 ten and 4 ones',
      '- 20 means 2 tens and 0 ones',
      '- 36 means 3 tens and 6 ones',
      '',
      'This is why we say "thirty-six" — three tens, then six.',
      '',
      '## Writing the numbers',
      '',
      '| Number | Word | Tens | Ones |',
      '| --- | --- | --- | --- |',
      '| 7 | seven | 0 | 7 |',
      '| 15 | fifteen | 1 | 5 |',
      '| 42 | forty-two | 4 | 2 |',
      '| 100 | one hundred | 10 tens | 0 |',
      '',
      '## Common mistakes',
      '',
      '- Saying "eleven-teen" instead of eleven. Eleven and twelve are special words.',
      '- Skipping numbers when counting past 19. Go 19, 20, 21 — not 19, 21.',
      '- Forgetting the hyphen in words like forty-two.',
      '',
      '## Practise',
      '',
      '1. Count from 55 to 70 out loud.',
      '2. Write the word for 83.',
      '3. How many tens are in 90?',
    ].join('\n'),
  },

  // ── PRIMARY — Standard 2 ──────────────────────────────────────────────
  {
    id: 'read-std2-math-1-numbers-1000',
    topicId: 'std2-math-1',
    title: 'Place value up to 1000',
    summary: 'Hundreds, tens and ones — reading, writing and comparing bigger numbers.',
    kind: 'lesson_note',
    readingMinutes: 6,
    sortOrder: 1,
    body: [
      '## The three places',
      '',
      'Every number up to 999 has three places, read from the right:',
      '',
      '- **ones** — the smallest place',
      '- **tens** — worth ten ones',
      '- **hundreds** — worth ten tens, or one hundred ones',
      '',
      'Example: in **472**',
      '',
      '- 4 is in the hundreds place, so it is worth 400',
      '- 7 is in the tens place, so it is worth 70',
      '- 2 is in the ones place, so it is worth 2',
      '',
      '400 + 70 + 2 = 472',
      '',
      '## Comparing numbers',
      '',
      'To decide which number is bigger, compare from the left.',
      '',
      '1. Look at the hundreds. 512 has 5 hundreds, 498 has 4 hundreds. So 512 is bigger.',
      '2. If the hundreds are equal, look at the tens.',
      '3. If the tens are equal too, look at the ones.',
      '',
      'The symbols are:',
      '',
      '- **>** means greater than — 512 > 498',
      '- **<** means less than — 498 < 512',
      '- **=** means equal to — 300 = 300',
      '',
      '## Zero as a placeholder',
      '',
      'Zero is not nothing — it holds a place open.',
      '',
      '- 305 means 3 hundreds, 0 tens, 5 ones',
      '',
      'Without the zero you would write 35, which is a completely different number.',
      '',
      '## Practise',
      '',
      '1. Write 608 in expanded form (hundreds + tens + ones).',
      '2. Which is larger: 799 or 801?',
      '3. Fill in the missing sign: 250 ___ 205',
    ].join('\n'),
  },

  // ── PRIMARY — Standard 3 ──────────────────────────────────────────────
  {
    id: 'read-std3-math-1-times-tables',
    topicId: 'std3-math-1',
    title: 'Learning your multiplication tables',
    summary: 'Patterns and shortcuts that make the 2, 5, 9 and 10 tables easy to remember.',
    kind: 'explainer',
    readingMinutes: 7,
    sortOrder: 1,
    body: [
      '## Multiplication is repeated addition',
      '',
      '4 × 3 means "four groups of three":',
      '',
      '3 + 3 + 3 + 3 = 12',
      '',
      'So 4 × 3 = 12.',
      '',
      '## The easy tables',
      '',
      '### The 10 table',
      'Just put a zero on the end. 7 × 10 = 70.',
      '',
      '### The 5 table',
      'Answers always end in 5 or 0, and they go up in fives:',
      '5, 10, 15, 20, 25, 30, 35, 40, 45, 50.',
      '',
      '### The 2 table',
      'Answers are always even: 2, 4, 6, 8, 10, 12 …',
      '',
      '### The 9 table',
      'The digits of every answer add up to 9.',
      '',
      '- 9 × 3 = 27, and 2 + 7 = 9',
      '- 9 × 7 = 63, and 6 + 3 = 9',
      '',
      'There is also a finger trick. Hold up ten fingers. To do 9 × 4, bend down the fourth',
      'finger from the left. You have 3 fingers on the left and 6 on the right, so the answer',
      'is 36.',
      '',
      '## Turning tables around',
      '',
      'Order does not matter: 3 × 8 = 8 × 3 = 24.',
      '',
      'This halves what you have to learn. If you know your 3 table, you already know part of',
      'your 8 table.',
      '',
      '## Practise',
      '',
      '1. 9 × 6 = ?',
      '2. 5 × 8 = ?',
      '3. If 7 × 4 = 28, what is 4 × 7?',
    ].join('\n'),
  },

  {
    id: 'read-std3-science-1-living-things',
    topicId: 'std3-science-1',
    title: 'What makes something living?',
    summary: 'The seven signs of life, with examples from around the home and school.',
    kind: 'lesson_note',
    readingMinutes: 6,
    sortOrder: 1,
    body: [
      '## Living and non-living',
      '',
      'A goat is living. A stone is not. But how do we know?',
      '',
      'Scientists use a checklist. Something is **living** if it does all of these things.',
      '',
      '## The signs of life',
      '',
      '1. **It grows.** A seedling becomes a tree. A baby becomes an adult.',
      '2. **It feeds.** Plants take in water and sunlight. Animals eat food.',
      '3. **It breathes.** Animals take in oxygen. Plants take in gases through their leaves.',
      '4. **It moves.** Animals walk, swim or fly. Plants turn towards the sun.',
      '5. **It gets rid of waste.** Animals sweat and use the toilet. Plants drop old leaves.',
      '6. **It reproduces.** It makes young ones — seeds, eggs or babies.',
      '7. **It senses.** It reacts to light, heat, touch or sound.',
      '',
      '## Tricky cases',
      '',
      '**A car moves and uses fuel.** But it does not grow, reproduce, or sense things.',
      'It is not alive.',
      '',
      '**A dry seed looks dead.** Put it in soil and water it, and it starts to grow. It was',
      'alive but resting.',
      '',
      '**A flame grows and moves.** But it does not feed, reproduce or sense. It is not alive.',
      '',
      '## Groups of living things',
      '',
      '- **Plants** — maize, mango trees, grass',
      '- **Animals** — cows, birds, fish, humans',
      '',
      '## Practise',
      '',
      '1. Name three living things in your classroom.',
      '2. Why is a bicycle not alive? Give two reasons.',
      '3. A seed is kept dry for one year. Is it alive? Explain.',
    ].join('\n'),
  },

  // ── PRIMARY — Standard 4 ──────────────────────────────────────────────
  {
    id: 'read-std4-math-1-long-multiplication',
    topicId: 'std4-math-1',
    title: 'Long multiplication step by step',
    summary: 'A reliable written method for multiplying two-digit numbers.',
    kind: 'lesson_note',
    readingMinutes: 8,
    sortOrder: 1,
    body: [
      '## When you need it',
      '',
      'You can do 6 × 7 in your head. You probably cannot do 47 × 36 in your head. For that we',
      'use **long multiplication** — a written method that always works.',
      '',
      '## Worked example: 47 × 36',
      '',
      '### Step 1 — Multiply by the ones digit',
      '',
      'Multiply 47 by 6 (the ones digit of 36):',
      '',
      '- 7 × 6 = 42. Write 2, carry 4.',
      '- 4 × 6 = 24, plus the carried 4 = 28.',
      '',
      'First row: **282**',
      '',
      '### Step 2 — Multiply by the tens digit',
      '',
      'Multiply 47 by 3 (the tens digit of 36). Because it is really 30, the answer shifts one',
      'place left, so start writing under the tens column:',
      '',
      '- 7 × 3 = 21. Write 1, carry 2.',
      '- 4 × 3 = 12, plus the carried 2 = 14.',
      '',
      'Second row, shifted left: **1410**',
      '',
      '### Step 3 — Add the rows',
      '',
      '   282',
      '+ 1410',
      '  -----',
      '  1692',
      '',
      'So 47 × 36 = **1692**.',
      '',
      '## Why the shift matters',
      '',
      'The most common mistake is forgetting to shift the second row. The 3 in 36 is worth 30,',
      'not 3, so 47 × 30 = 1410 — ten times bigger than 47 × 3.',
      '',
      '## Check your answer',
      '',
      'Estimate first: 47 is about 50, and 36 is about 40. So the answer should be near',
      '50 × 40 = 2000. Our answer, 1692, is close. Good.',
      '',
      'If your estimate and your answer are far apart, look for a mistake.',
      '',
      '## Practise',
      '',
      '1. 34 × 21',
      '2. 56 × 43',
      '3. 78 × 65',
    ].join('\n'),
  },

  {
    id: 'read-std4-civics-1-rights-duties',
    topicId: 'std4-civics-1',
    title: 'Rights and duties of a citizen',
    summary: 'What every Tanzanian is entitled to, and what every citizen owes in return.',
    kind: 'lesson_note',
    readingMinutes: 6,
    sortOrder: 1,
    body: [
      '## What is a right?',
      '',
      'A **right** is something you are entitled to simply because you are a person and a',
      'citizen. Nobody has to earn it, and nobody can take it away unfairly.',
      '',
      '## What is a duty?',
      '',
      'A **duty** is something you owe to your country and your community. Rights and duties go',
      'together — you cannot claim one without accepting the other.',
      '',
      '## Rights in the Constitution',
      '',
      'The Constitution of the United Republic of Tanzania guarantees, among others:',
      '',
      '- The right to **life**',
      '- The right to **equality** before the law',
      '- The right to **education**',
      '- The right to **work** and to be paid fairly',
      '- Freedom of **expression**, religion and association',
      '- The right to **own property**',
      '',
      '## Duties of a citizen',
      '',
      '- **Pay taxes** honestly — this is what funds schools, hospitals and roads',
      '- **Obey the law**',
      '- **Respect other people** and their rights',
      '- **Protect public property** — do not vandalise desks, taps or street lights',
      '- **Defend the nation** when called upon',
      '- **Care for the environment** — plant trees, do not dump waste in rivers',
      '- **Vote** in elections when you are old enough',
      '',
      '## Rights and duties in school',
      '',
      '| Your right at school | Your duty at school |',
      '| --- | --- |',
      '| To be taught well | To attend class and listen |',
      '| To be safe from bullying | To not bully others |',
      '| To use the library and labs | To return what you borrow, in good condition |',
      '',
      '## Practise',
      '',
      '1. Name three rights from the Constitution.',
      '2. Why must citizens pay taxes?',
      '3. A classmate scribbles on a desk. Which duty have they broken?',
    ].join('\n'),
  },

  // ── PRIMARY — Standard 5 ──────────────────────────────────────────────
  {
    id: 'read-std5-math-1-percentages',
    topicId: 'std5-math-1',
    title: 'Percentages made simple',
    summary: 'Convert between fractions, decimals and percentages, and find a percentage of any number.',
    kind: 'explainer',
    readingMinutes: 8,
    sortOrder: 1,
    body: [
      '## What "per cent" means',
      '',
      '"Per cent" means **per hundred**. So 25% means 25 out of every 100.',
      '',
      '25% = 25/100 = 0.25',
      '',
      'That single idea is enough to convert between percentages, fractions and decimals.',
      '',
      '## Converting',
      '',
      '**Percent to decimal** — divide by 100 (move the point two places left).',
      '63% = 0.63',
      '',
      '**Decimal to percent** — multiply by 100 (move the point two places right).',
      '0.07 = 7%',
      '',
      '**Fraction to percent** — multiply by 100.',
      '3/4 × 100 = 75%',
      '',
      '**Percent to fraction** — put it over 100 and simplify.',
      '40% = 40/100 = 2/5',
      '',
      '## Finding a percentage of a number',
      '',
      'To find 30% of 250:',
      '',
      '1. Convert to a decimal: 30% = 0.30',
      '2. Multiply: 0.30 × 250 = 75',
      '',
      'So 30% of 250 is **75**.',
      '',
      '## The 10% shortcut',
      '',
      '10% is easy — just divide by 10. From there you can build anything.',
      '',
      'Find 35% of 80:',
      '',
      '- 10% of 80 = 8',
      '- 30% is three lots of 10%, so 3 × 8 = 24',
      '- 5% is half of 10%, so 8 ÷ 2 = 4',
      '- 35% = 30% + 5% = 24 + 4 = **28**',
      '',
      '## Percentages in real life',
      '',
      '**Discounts.** A shirt costs 20,000 shillings with 15% off.',
      '15% of 20,000 = 3,000. You pay 20,000 − 3,000 = **17,000**.',
      '',
      '**Marks.** You score 36 out of 40. 36 ÷ 40 = 0.9, so 90%.',
      '',
      '## Practise',
      '',
      '1. Write 45% as a fraction in simplest form.',
      '2. Find 15% of 400.',
      '3. A bag of rice costs 60,000 shillings. The price rises by 20%. What is the new price?',
    ].join('\n'),
  },

  {
    id: 'read-std5-geo-2-tanzania-regions',
    topicId: 'std5-geo-2',
    title: 'The regions of Tanzania',
    summary: 'How the country is divided, where the main regions sit, and how to remember them.',
    kind: 'reference',
    readingMinutes: 7,
    sortOrder: 1,
    body: [
      '## How Tanzania is organised',
      '',
      'Tanzania is divided into **regions**, each region into **districts**, each district into',
      '**wards**, and each ward into **villages** or **streets**.',
      '',
      'The country has **31 regions** — 26 on the mainland and 5 in Zanzibar.',
      '',
      '## Zanzibar',
      '',
      'The five regions of Zanzibar are:',
      '',
      '- Unguja North',
      '- Unguja South',
      '- Urban West',
      '- Pemba North',
      '- Pemba South',
      '',
      '## Mainland regions by zone',
      '',
      '### Northern zone',
      'Arusha, Kilimanjaro, Manyara, Tanga',
      '',
      '### Lake zone',
      'Mwanza, Mara, Kagera, Geita, Simiyu, Shinyanga',
      '',
      '### Central zone',
      'Dodoma (the national capital), Singida, Tabora',
      '',
      '### Southern highlands',
      'Mbeya, Iringa, Njombe, Ruvuma, Songwe',
      '',
      '### Southern zone',
      'Mtwara, Lindi',
      '',
      '### Coastal / Eastern zone',
      'Dar es Salaam (largest city), Pwani, Morogoro',
      '',
      '### Western zone',
      'Kigoma, Katavi, Rukwa',
      '',
      '## Facts worth remembering',
      '',
      '- **Dodoma** is the official capital.',
      '- **Dar es Salaam** is the largest city and main port.',
      '- **Mount Kilimanjaro**, the highest mountain in Africa, is in Kilimanjaro region.',
      '- **Lake Victoria**, the largest lake in Africa, borders Mwanza, Mara and Kagera.',
      '- Tanzania borders Kenya, Uganda, Rwanda, Burundi, the DRC, Zambia, Malawi and Mozambique.',
      '',
      '## Practise',
      '',
      '1. Name the three regions of the Northern zone.',
      '2. Which region is the national capital in?',
      '3. How many regions does Zanzibar have?',
    ].join('\n'),
  },

  // ── PRIMARY — Standard 6 ──────────────────────────────────────────────
  {
    id: 'read-std6-math-1-algebra-basics',
    topicId: 'std6-math-1',
    title: 'Introduction to algebra',
    summary: 'Letters as unknown numbers, and how to simplify and solve simple expressions.',
    kind: 'lesson_note',
    readingMinutes: 8,
    sortOrder: 1,
    body: [
      '## Why letters?',
      '',
      'Sometimes we do not know a number yet. We give it a name — usually a letter — and work',
      'with it anyway.',
      '',
      'If a pen costs x shillings, then five pens cost 5x shillings. We can write that down',
      'before we know the price.',
      '',
      '## Writing expressions',
      '',
      '- 3 × a is written **3a**',
      '- a × b is written **ab**',
      '- 1 × a is written **a**, not 1a',
      '',
      '## Terms and like terms',
      '',
      'A **term** is a part of an expression separated by + or −.',
      '',
      'In 4a + 3b − 2a + 7b:',
      '',
      '- The terms are 4a, 3b, −2a and 7b',
      '- **Like terms** have the same letter: 4a and −2a are like; 3b and 7b are like',
      '',
      'You can only combine like terms.',
      '',
      '4a + 3b − 2a + 7b',
      '= (4a − 2a) + (3b + 7b)',
      '= **2a + 10b**',
      '',
      '## Solving simple equations',
      '',
      'The rule is: whatever you do to one side, do to the other.',
      '',
      'Solve 3x + 5 = 20:',
      '',
      '1. Subtract 5 from both sides: 3x = 15',
      '2. Divide both sides by 3: x = 5',
      '',
      '**Check:** 3 × 5 + 5 = 15 + 5 = 20. Correct.',
      '',
      '## Substitution',
      '',
      'If a = 4 and b = 2, find 3a + 5b.',
      '',
      '3(4) + 5(2) = 12 + 10 = **22**',
      '',
      '## Practise',
      '',
      '1. Simplify: 7m + 2n − 3m + 5n',
      '2. Solve: 4y − 3 = 17',
      '3. If p = 3 and q = 5, find 2p + 4q',
    ].join('\n'),
  },

  {
    id: 'read-std6-hist-1-precolonial',
    topicId: 'std6-hist-1',
    title: 'Tanzania before colonial rule',
    summary: 'Trade, kingdoms and societies in the area of modern Tanzania before the 1880s.',
    kind: 'reference',
    readingMinutes: 8,
    sortOrder: 1,
    body: [
      '## The long view',
      '',
      'Long before Europeans arrived, the area of modern Tanzania was home to thriving',
      'societies with their own trade, politics and culture. Tanzania is the site of some of',
      'the earliest human remains ever found.',
      '',
      '## Early societies',
      '',
      '**Hunter-gatherers.** Groups such as the Hadzabe lived by hunting and gathering, as some',
      'still do today in the Lake Eyasi area.',
      '',
      '**Pastoralists.** The Maasai and other groups kept cattle and moved with their herds in',
      'search of grass and water.',
      '',
      '**Agriculturalists.** The Chagga on the slopes of Kilimanjaro built irrigated farms and',
      'grew bananas, yams and millet. The Sukuma and Nyamwezi farmed the western plains.',
      '',
      '## Iron and technology',
      '',
      'Iron-working reached the region over two thousand years ago. Iron tools made farming and',
      'building far more productive, and iron weapons changed how societies defended themselves.',
      '',
      '## Trade',
      '',
      '### Long-distance trade',
      'Caravans carried ivory, slaves and salt from the interior to the coast, and brought back',
      'cloth, beads, guns and metal goods. Nyamwezi traders were famous as caravan leaders.',
      '',
      '### The Swahili coast',
      'Towns such as Kilwa, Mombasa and Zanzibar grew rich on Indian Ocean trade, linking',
      'Africa to Arabia, Persia, India and China. Kilwa was a major centre for gold and ivory.',
      'The Swahili language and culture grew out of this mixing of African and Arab influence.',
      '',
      '## Kingdoms and leaders',
      '',
      '- **The Chagga** were organised into chiefdoms on Kilimanjaro.',
      '- **The Nyamwezi** built powerful chiefdoms under leaders such as Mirambo.',
      '- **The Hehe** under Chief Mkwawa later resisted German rule fiercely.',
      '',
      '## Why this matters',
      '',
      'Colonial history often starts with the arrival of Europeans. That misses the point:',
      'these societies already had government, trade, religion and technology. Understanding',
      'that makes the colonial period easier to understand too.',
      '',
      '## Practise',
      '',
      '1. Name two groups of pastoralists in Tanzania.',
      '2. What goods were carried from the interior to the coast?',
      '3. Why was Kilwa important?',
    ].join('\n'),
  },

  // ── PRIMARY — Standard 7 ──────────────────────────────────────────────
  {
    id: 'read-std7-math-1-problem-solving',
    topicId: 'std7-math-1',
    title: 'Solving word problems with confidence',
    summary: 'A four-step method that turns any word problem into an equation you can solve.',
    kind: 'explainer',
    readingMinutes: 9,
    sortOrder: 1,
    body: [
      '## Why word problems feel hard',
      '',
      'The maths is usually not the hard part — the difficulty is working out *what to do*.',
      'Use the same four steps every time and it becomes routine.',
      '',
      '## The four steps',
      '',
      '1. **Read and understand.** Read twice. Underline what you are asked to find.',
      '2. **Translate.** Turn the words into an equation. Choose a letter for the unknown.',
      '3. **Solve.** Do the arithmetic carefully.',
      '4. **Check.** Does the answer make sense? Put it back into the words.',
      '',
      '## Worked example',
      '',
      '> Amina has 3 times as many goats as Bakari. Together they have 48 goats.',
      '> How many does Bakari have?',
      '',
      '**Step 1.** Find Bakari\'s goats. Call that number b.',
      '',
      '**Step 2.** Amina has 3 times as many, so she has 3b. Together they have 48:',
      '',
      'b + 3b = 48',
      '',
      '**Step 3.**',
      '',
      '4b = 48',
      'b = 12',
      '',
      '**Step 4.** Bakari has 12. Amina has 3 × 12 = 36. Together 12 + 36 = 48. Correct.',
      '',
      '**Answer: Bakari has 12 goats.**',
      '',
      '## Words that give away the operation',
      '',
      '| Words | Usually means |',
      '| --- | --- |',
      '| sum, total, altogether, more than | addition |',
      '| difference, less than, fewer, how many left | subtraction |',
      '| times, product, each, every | multiplication |',
      '| share, per, split, how many each | division |',
      '',
      '## Warning: "less than" reverses order',
      '',
      '"5 less than x" is **x − 5**, not 5 − x. Read carefully.',
      '',
      '## Practise',
      '',
      '1. A trader sells 3 times as many oranges on Saturday as on Friday. Over both days she',
      '   sells 240 oranges. How many did she sell on Friday?',
      '2. The sum of two numbers is 90. One is twice the other. Find both.',
      '3. A tank holds 500 litres. It is 40% full. How many litres are in it?',
    ].join('\n'),
  },

  {
    id: 'read-std7-science-1-human-body',
    topicId: 'std7-science-1',
    title: 'Systems of the human body',
    summary: 'The main body systems, what each one does, and how they work together.',
    kind: 'lesson_note',
    readingMinutes: 8,
    sortOrder: 1,
    body: [
      '## Cells, tissues, organs, systems',
      '',
      'Cells group into **tissues**. Tissues group into **organs**. Organs that work together',
      'form a **system**. Your body has several systems, each with a job.',
      '',
      '## The main systems',
      '',
      '### Digestive system',
      'Breaks food into nutrients the body can use.',
      'Organs: mouth, oesophagus, stomach, small intestine, large intestine, liver, pancreas.',
      'Food travels about 9 metres from mouth to exit.',
      '',
      '### Respiratory system',
      'Takes in oxygen and removes carbon dioxide.',
      'Organs: nose, trachea, bronchi, lungs, diaphragm.',
      'The diaphragm is the muscle below the lungs that pulls air in.',
      '',
      '### Circulatory system',
      'Carries blood, nutrients and oxygen around the body.',
      'Organs: heart, blood vessels (arteries, veins, capillaries).',
      'The heart beats about 70 times a minute at rest and pumps blood in one direction only,',
      'kept on course by valves.',
      '',
      '### Nervous system',
      'Sends and receives messages, and controls everything else.',
      'Organs: brain, spinal cord, nerves.',
      'The brain is the control centre; the spinal cord is the main cable.',
      '',
      '### Skeletal and muscular systems',
      'The skeleton supports the body, protects organs and makes blood cells. Muscles pull on',
      'bones to create movement. The skull protects the brain; the ribcage protects the heart',
      'and lungs.',
      '',
      '### Excretory system',
      'Removes waste. Organs: kidneys, bladder, skin, lungs.',
      'The kidneys filter blood and make urine.',
      '',
      '## How they work together',
      '',
      'Run for a bus and watch the systems cooperate:',
      '',
      '1. Muscles need more oxygen, so the **nervous system** signals the heart.',
      '2. The **heart** beats faster and the **lungs** breathe deeper.',
      '3. The **digestive system** supplies the glucose being burned.',
      '4. The **excretory system** clears the waste produced.',
      '',
      '## Keeping systems healthy',
      '',
      '- Eat a balanced diet — carbohydrates, proteins, vitamins, minerals, water',
      '- Exercise regularly — strengthens the heart and muscles',
      '- Avoid smoking and alcohol — they damage lungs, liver and heart',
      '- Sleep 8 to 10 hours — the body repairs itself',
      '- Drink clean water — prevents cholera and typhoid',
      '',
      '## Practise',
      '',
      '1. Which system carries oxygen around the body?',
      '2. Name the muscle that pulls air into the lungs.',
      '3. Give two ways to keep your heart healthy.',
    ].join('\n'),
  },

  // ── SECONDARY — Form 1 ────────────────────────────────────────────────
  {
    id: 'read-f1-math-1-real-numbers',
    topicId: 'f1-math-1',
    title: 'The real number system',
    summary: 'Natural, whole, integer, rational and irrational numbers, and how they nest.',
    kind: 'lesson_note',
    readingMinutes: 8,
    sortOrder: 1,
    body: [
      '## The number sets',
      '',
      'Numbers come in families. Each family contains the one before it.',
      '',
      '### Natural numbers (N)',
      'Counting numbers: 1, 2, 3, 4, …',
      '',
      '### Whole numbers (W)',
      'Natural numbers plus zero: 0, 1, 2, 3, …',
      '',
      '### Integers (Z)',
      'Whole numbers and their negatives: …, −2, −1, 0, 1, 2, …',
      '',
      '### Rational numbers (Q)',
      'Any number that can be written as a fraction a/b, where a and b are integers and b ≠ 0.',
      'Examples: 3/4, −5, 0.25, 0.333…',
      '',
      'Every terminating decimal and every recurring decimal is rational.',
      '',
      '### Irrational numbers (Q\')',
      'Numbers that **cannot** be written as a fraction. Their decimals never end and never',
      'repeat. Examples: √2, √3, π, e.',
      '',
      '### Real numbers (R)',
      'All rational and irrational numbers together. Everything on the number line.',
      '',
      '## The nesting',
      '',
      'N ⊂ W ⊂ Z ⊂ Q ⊂ R',
      '',
      'Every natural number is a whole number. Every whole number is an integer. Every integer',
      'is rational (5 = 5/1). But not every rational number is an integer.',
      '',
      '## Worked examples',
      '',
      '**Classify −7.** It is an integer, a rational number, and a real number. It is not natural.',
      '',
      '**Classify 0.75.** It is rational (3/4) and real. It is not an integer.',
      '',
      '**Is √9 irrational?** No. √9 = 3, which is a natural number. A surd is only irrational',
      'when the root is not exact.',
      '',
      '## The number line',
      '',
      'Every real number has exactly one point on the number line, and every point has exactly',
      'one real number. This one-to-one match is what makes the number line so useful.',
      '',
      '## Practise',
      '',
      '1. List all the integers between −3 and 3.',
      '2. Classify each as rational or irrational: 0.5, √7, 22/7, π, −4.',
      '3. Explain why every integer is a rational number.',
    ].join('\n'),
  },

  {
    id: 'read-f1-phy-1-measurements',
    topicId: 'f1-phy-1',
    title: 'Measurement and SI units',
    summary: 'Base and derived units, prefixes, and how to record a measurement honestly.',
    kind: 'lesson_note',
    readingMinutes: 8,
    sortOrder: 1,
    body: [
      '## Why measurement matters',
      '',
      'Physics is a quantitative science. A statement like "the table is long" is not useful.',
      '"The table is 1.52 metres long" is. Every measurement needs a **number** and a **unit**.',
      '',
      '## SI base quantities',
      '',
      '| Quantity | Unit | Symbol |',
      '| --- | --- | --- |',
      '| Length | metre | m |',
      '| Mass | kilogram | kg |',
      '| Time | second | s |',
      '| Electric current | ampere | A |',
      '| Temperature | kelvin | K |',
      '| Amount of substance | mole | mol |',
      '| Luminous intensity | candela | cd |',
      '',
      '## Derived units',
      '',
      'Derived units are built from base units.',
      '',
      '- **Area** = m × m = m²',
      '- **Volume** = m³',
      '- **Speed** = distance ÷ time = m/s',
      '- **Density** = mass ÷ volume = kg/m³',
      '- **Force** = mass × acceleration = kg·m/s² = the newton (N)',
      '',
      '## Prefixes',
      '',
      '| Prefix | Symbol | Factor |',
      '| --- | --- | --- |',
      '| kilo | k | 10³ |',
      '| centi | c | 10⁻² |',
      '| milli | m | 10⁻³ |',
      '| micro | µ | 10⁻⁶ |',
      '| nano | n | 10⁻⁹ |',
      '',
      'So 1 km = 1000 m, and 1 mg = 0.001 g.',
      '',
      '## Significant figures',
      '',
      'A measurement can never be perfectly exact. The digits you write should show how precise',
      'you actually were.',
      '',
      '**Rules:**',
      '',
      '1. All non-zero digits count: 4.62 has 3 s.f.',
      '2. Zeros between non-zero digits count: 3.05 has 3 s.f.',
      '3. Leading zeros do not count: 0.0025 has 2 s.f.',
      '4. Trailing zeros after a decimal point count: 2.50 has 3 s.f.',
      '',
      '## Recording a reading',
      '',
      'If a ruler has millimetre marks, you can honestly record to the nearest millimetre, plus',
      'one estimated digit. Writing 15.24 cm from that ruler overstates your precision.',
      '',
      '## Practise',
      '',
      '1. Express 3.5 km in metres.',
      '2. How many significant figures in 0.0406?',
      '3. Derive the SI unit of pressure from force and area.',
    ].join('\n'),
  },

  {
    id: 'read-f1-chem-1-lab-safety',
    topicId: 'f1-chem-1',
    title: 'Laboratory safety rules',
    summary: 'The rules that keep you safe, the common hazard symbols, and what to do in an emergency.',
    kind: 'reference',
    readingMinutes: 7,
    sortOrder: 1,
    body: [
      '## Before you start',
      '',
      '- Wear safety goggles and a lab coat',
      '- Tie back long hair and remove loose jewellery',
      '- Never eat or drink in the laboratory',
      '- Read the method fully before touching anything',
      '- Know where the fire extinguisher, first aid kit, eyewash and exit are',
      '',
      '## While working',
      '',
      '- Never taste or smell a chemical directly. To smell safely, waft the vapour towards you',
      '- Point test tubes away from yourself and others when heating',
      '- Use a test-tube holder, never bare fingers',
      '- Add acid to water, **never water to acid** — the reverse can splash and burn',
      '- Keep your bench clear and your bag out of the walkway',
      '- Label every container you use',
      '- Never return unused chemicals to the original bottle',
      '',
      '## Hazard symbols',
      '',
      '| Symbol | Meaning |',
      '| --- | --- |',
      '| Flame | Flammable — catches fire easily |',
      '| Skull and crossbones | Toxic — poisonous |',
      '| Corrosive | Destroys skin and metal |',
      '| Oxidising | Can cause or feed fire |',
      '| Explosive | Can explode |',
      '| Environmental hazard | Dangerous to living things in water |',
      '',
      '## Common apparatus',
      '',
      '- **Beaker** — mixing and heating liquids roughly',
      '- **Conical flask** — mixing and swirling, easy to stopper',
      '- **Measuring cylinder** — measuring liquid volumes accurately',
      '- **Burette** — very accurate volume delivery in titrations',
      '- **Pipette** — delivering one exact volume',
      '- **Evaporating dish** — heating a solution to crystallisation',
      '',
      'Read a measuring cylinder at eye level, and read the **bottom of the meniscus**.',
      '',
      '## In an emergency',
      '',
      '1. **Chemical on skin** — rinse with plenty of running water for 15 minutes.',
      '2. **Chemical in eyes** — go straight to the eyewash, hold the eye open, rinse 15 minutes.',
      '3. **Fire** — raise the alarm, turn off gas, leave by the nearest exit. Never use water on',
      '   an electrical or oil fire.',
      '4. **Broken glass** — do not pick it up with your hands. Use a dustpan and brush.',
      '5. **Any accident, however small** — tell the teacher immediately.',
      '',
      '## Practise',
      '',
      '1. Why is acid added to water, and not water to acid?',
      '2. Name the apparatus used for accurate titration.',
      '3. What should you do first if a chemical splashes in your eye?',
    ].join('\n'),
  },

  // ── SECONDARY — Form 2 ────────────────────────────────────────────────
  {
    id: 'read-f2-math-1-simultaneous',
    topicId: 'f2-math-1',
    title: 'Simultaneous equations: substitution and elimination',
    summary: 'Two methods for solving two equations with two unknowns, worked side by side.',
    kind: 'lesson_note',
    readingMinutes: 10,
    sortOrder: 1,
    body: [
      '## The problem',
      '',
      'One equation with two unknowns has infinitely many answers. Two equations together often',
      'pin down exactly one pair.',
      '',
      'Solve:',
      '',
      '    2x + y = 11',
      '    x − y = 1',
      '',
      '## Method 1 — Elimination',
      '',
      'The idea is to add or subtract the equations so one letter disappears.',
      '',
      'Here the y terms are already +y and −y. Add the equations:',
      '',
      '    (2x + y) + (x − y) = 11 + 1',
      '    3x = 12',
      '    x = 4',
      '',
      'Substitute back into the simpler equation:',
      '',
      '    4 − y = 1',
      '    y = 3',
      '',
      '**Solution: x = 4, y = 3.**',
      '',
      'Check in the other equation: 2(4) + 3 = 8 + 3 = 11. Correct.',
      '',
      '### When the coefficients do not match',
      '',
      'Solve:',
      '',
      '    3x + 2y = 16',
      '    2x + 5y = 18',
      '',
      'Multiply the first by 5 and the second by 2 so the y terms match:',
      '',
      '    15x + 10y = 80',
      '     4x + 10y = 36',
      '',
      'Subtract: 11x = 44, so x = 4. Then 3(4) + 2y = 16, so 2y = 4 and y = 2.',
      '',
      '## Method 2 — Substitution',
      '',
      'Rearrange one equation for one letter, then replace it in the other.',
      '',
      '    y = 2x + 1',
      '    3x + 2y = 12',
      '',
      'Substitute the first into the second:',
      '',
      '    3x + 2(2x + 1) = 12',
      '    3x + 4x + 2 = 12',
      '    7x = 10',
      '    x = 10/7',
      '',
      'Then y = 2(10/7) + 1 = 27/7.',
      '',
      '## Which method to choose',
      '',
      '- If one equation already has a letter alone (y = … or x = …), **substitute**.',
      '- If the coefficients are close to matching, **eliminate** — it usually involves less',
      '  fraction work.',
      '',
      '## Special cases',
      '',
      '**No solution.** Parallel lines. 2x + y = 5 and 2x + y = 9. Same left side, different',
      'right side — impossible.',
      '',
      '**Infinite solutions.** The same line twice. x + y = 4 and 2x + 2y = 8. The second is',
      'just the first doubled, so it adds no new information.',
      '',
      '## Practise',
      '',
      '1. Solve: x + y = 10 and x − y = 4',
      '2. Solve: 3x + y = 13 and x + 2y = 11',
      '3. Solve by substitution: y = 3x − 2 and 2x + y = 8',
    ].join('\n'),
  },

  // ── SECONDARY — Form 4 ────────────────────────────────────────────────
  {
    id: 'read-f4-math-1-matrices',
    topicId: 'f4-math-1',
    title: 'Matrices and transformations',
    summary: 'Matrix order, addition, multiplication, determinants and inverses, plus the transformation matrices.',
    kind: 'lesson_note',
    readingMinutes: 11,
    sortOrder: 1,
    body: [
      '## What a matrix is',
      '',
      'A matrix is a rectangular arrangement of numbers in rows and columns, written in brackets.',
      '',
      '    A = [ 2  3 ]',
      '        [ 1  4 ]',
      '',
      'A has **2 rows and 2 columns**, so its order is 2 × 2. Order is always written rows first.',
      '',
      '## Addition and subtraction',
      '',
      'You can only add matrices of the **same order**. Add matching positions.',
      '',
      '    [1 2]   [5 6]   [6  8]',
      '    [3 4] + [7 8] = [10 12]',
      '',
      '## Multiplication',
      '',
      'To multiply, the **columns of the first** must equal the **rows of the second**.',
      'The result takes the outer dimensions.',
      '',
      '    (2×3) × (3×4) → 2×4',
      '',
      'Each entry is a row-times-column dot product:',
      '',
      '    [1 2]   [5 6]   [1(5)+2(7)   1(6)+2(8)]   [19 22]',
      '    [3 4] × [7 8] = [3(5)+4(7)   3(6)+4(8)] = [43 50]',
      '',
      '**Order matters.** AB is usually not the same as BA.',
      '',
      '## Determinant',
      '',
      'For a 2 × 2 matrix:',
      '',
      '    det [a b]',
      '        [c d] = ad − bc',
      '',
      'For A above: det A = 2(4) − 3(1) = 8 − 3 = 5.',
      '',
      '## Inverse',
      '',
      'The inverse of a 2 × 2 matrix swaps a and d, negates b and c, and divides by the',
      'determinant:',
      '',
      '    A⁻¹ = 1/det(A) × [ d  −b ]',
      '                    [−c   a ]',
      '',
      'A matrix has no inverse when det = 0. It is then called **singular**.',
      '',
      '**Use:** solving simultaneous equations. Write AX = B, then X = A⁻¹B.',
      '',
      '## Transformation matrices',
      '',
      '| Transformation | Matrix |',
      '| --- | --- |',
      '| Reflection in the x-axis | [1 0 / 0 −1] |',
      '| Reflection in the y-axis | [−1 0 / 0 1] |',
      '| Reflection in y = x | [0 1 / 1 0] |',
      '| Rotation 90° anticlockwise about O | [0 −1 / 1 0] |',
      '| Rotation 180° about O | [−1 0 / 0 −1] |',
      '| Enlargement, scale factor k | [k 0 / 0 k] |',
      '',
      'To find the image of a point, write it as a column vector and multiply.',
      '',
      '## Practise',
      '',
      '1. Find det [6 2 / 1 3].',
      '2. Multiply [1 0 / 0 2] by [3 / 5]. Describe the transformation.',
      '3. Find the inverse of [4 1 / 3 1].',
    ].join('\n'),
  },

  // ── A-LEVEL — Form 5 ──────────────────────────────────────────────────
  {
    id: 'read-f5-math-1-calculus',
    topicId: 'f5-math-1',
    title: 'Differentiation from first principles',
    summary: 'Where the derivative comes from, the standard rules, and what it means geometrically.',
    kind: 'explainer',
    readingMinutes: 12,
    sortOrder: 1,
    body: [
      '## The central idea',
      '',
      'The derivative measures the **rate of change** of a function. Geometrically, it is the',
      'gradient of the tangent to the curve at a point.',
      '',
      '## Gradient of a chord, then a tangent',
      '',
      'Take two points on y = f(x), at x and x + h. The gradient of the chord between them is:',
      '',
      '    [f(x + h) − f(x)] / h',
      '',
      'Now let h shrink towards zero. The chord pivots towards the tangent. The limit is the',
      'derivative:',
      '',
      '    f\'(x) = lim (h→0) [f(x + h) − f(x)] / h',
      '',
      '## Worked example: y = x²',
      '',
      '    f(x + h) = (x + h)² = x² + 2xh + h²',
      '',
      '    [f(x + h) − f(x)] / h = (x² + 2xh + h² − x²) / h',
      '                          = (2xh + h²) / h',
      '                          = 2x + h',
      '',
      'As h → 0, the result tends to 2x. So:',
      '',
      '    d/dx (x²) = 2x',
      '',
      '## The power rule',
      '',
      'The pattern generalises:',
      '',
      '    d/dx (xⁿ) = n·xⁿ⁻¹',
      '',
      'Examples:',
      '',
      '- d/dx (x³) = 3x²',
      '- d/dx (x) = 1',
      '- d/dx (7) = 0 — a constant does not change',
      '- d/dx (x⁻¹) = −x⁻²',
      '- d/dx (√x) = d/dx (x^½) = ½x^−½',
      '',
      '## Rules for combining',
      '',
      '**Constant multiple:** d/dx [k·f(x)] = k·f\'(x)',
      '',
      '**Sum:** differentiate term by term.',
      '',
      '    d/dx (3x² + 5x − 4) = 6x + 5',
      '',
      '**Product:** (uv)\' = u\'v + uv\'',
      '',
      '**Quotient:** (u/v)\' = (u\'v − uv\') / v²',
      '',
      '**Chain rule:** if y = f(g(x)), then dy/dx = f\'(g(x)) · g\'(x)',
      '',
      '## What the derivative tells you',
      '',
      '- f\'(x) > 0 — the function is increasing',
      '- f\'(x) < 0 — the function is decreasing',
      '- f\'(x) = 0 — a stationary point (maximum, minimum, or point of inflection)',
      '',
      'This is how you find maximum profit, minimum cost, or the peak of a projectile.',
      '',
      '## Practise',
      '',
      '1. Differentiate y = 4x³ − 2x² + 7x − 1.',
      '2. Find the gradient of y = x² at x = 3.',
      '3. Find the stationary point of y = x² − 6x + 5 and say whether it is a maximum or minimum.',
    ].join('\n'),
  },

  {
    id: 'read-f5-phy-1-mechanics',
    topicId: 'f5-phy-1',
    title: "Newton's laws of motion",
    summary: 'The three laws, free-body diagrams, and worked problems with friction and inclined planes.',
    kind: 'lesson_note',
    readingMinutes: 11,
    sortOrder: 1,
    body: [
      '## Newton\'s first law — inertia',
      '',
      'An object stays at rest, or moves at constant velocity, unless a **resultant force** acts',
      'on it.',
      '',
      'A book on a table is not "naturally still" — gravity pulls it down and the table pushes',
      'up, and the two cancel. Zero resultant force means no change in motion.',
      '',
      '## Newton\'s second law — F = ma',
      '',
      'Resultant force equals mass times acceleration.',
      '',
      '    F = ma',
      '',
      '- F in newtons (N)',
      '- m in kilograms (kg)',
      '- a in metres per second squared (m/s²)',
      '',
      '**Important:** F is the *resultant* force, not any single force. Always find the vector',
      'sum first.',
      '',
      '## Newton\'s third law — action and reaction',
      '',
      'If A exerts a force on B, then B exerts an equal and opposite force on A.',
      '',
      'These forces act on **different objects**, which is why they do not cancel. When you',
      'push a wall, the wall pushes you back.',
      '',
      '## Weight vs mass',
      '',
      'Mass is the amount of matter (kg) and does not change. Weight is the gravitational force',
      'on that mass:',
      '',
      '    W = mg    where g ≈ 9.8 m/s² near the Earth\'s surface',
      '',
      'A 60 kg student has a weight of 60 × 9.8 = 588 N.',
      '',
      '## Free-body diagrams',
      '',
      'Draw every force on the object as an arrow:',
      '',
      '1. **Weight** — straight down, always',
      '2. **Normal reaction** — perpendicular to the surface',
      '3. **Tension** — along a string, away from the object',
      '4. **Friction** — along the surface, opposing motion',
      '',
      '## Worked problem',
      '',
      '> A 5 kg block is pulled along a rough floor by a 30 N force. Friction is 8 N.',
      '> Find the acceleration.',
      '',
      'Resultant force: 30 − 8 = 22 N',
      '',
      '    a = F/m = 22/5 = 4.4 m/s²',
      '',
      '## On an inclined plane',
      '',
      'The component of weight down the slope is mg·sin θ. The normal reaction is mg·cos θ.',
      'For a 2 kg block on a 30° frictionless slope:',
      '',
      '    a = g·sin 30° = 9.8 × 0.5 = 4.9 m/s²',
      '',
      'Notice the mass cancels — on a frictionless slope, all objects accelerate the same.',
      '',
      '## Practise',
      '',
      '1. A 1200 kg car accelerates at 2 m/s². What resultant force acts on it?',
      '2. A 10 kg box sits on a table. What is the normal reaction?',
      '3. A 3 kg mass hangs on a string. Find the tension when it is at rest.',
    ].join('\n'),
  },

  // ── A-LEVEL — Form 6 ──────────────────────────────────────────────────
  {
    id: 'read-f6-math-1-advanced-calculus',
    topicId: 'f6-math-1',
    title: 'Integration techniques',
    summary: 'Substitution, integration by parts, and definite integrals with areas under curves.',
    kind: 'lesson_note',
    readingMinutes: 12,
    sortOrder: 1,
    body: [
      '## Integration is anti-differentiation',
      '',
      'If d/dx [F(x)] = f(x), then ∫f(x) dx = F(x) + c.',
      '',
      'The constant c matters: infinitely many functions have the same derivative. It is only',
      'determined when you know one point, or when the integral is definite.',
      '',
      '## Standard results',
      '',
      '| Integral | Result |',
      '| --- | --- |',
      '| ∫xⁿ dx | xⁿ⁺¹/(n+1) + c, for n ≠ −1 |',
      '| ∫1/x dx | ln\\|x\\| + c |',
      '| ∫eˣ dx | eˣ + c |',
      '| ∫sin x dx | −cos x + c |',
      '| ∫cos x dx | sin x + c |',
      '| ∫sec²x dx | tan x + c |',
      '',
      '## Substitution',
      '',
      'Use when an integral contains a function and its derivative.',
      '',
      'Find ∫2x(x² + 1)⁵ dx:',
      '',
      '1. Let u = x² + 1',
      '2. Then du/dx = 2x, so du = 2x dx',
      '3. The integral becomes ∫u⁵ du = u⁶/6 + c',
      '4. Substitute back: **(x² + 1)⁶/6 + c**',
      '',
      '## Integration by parts',
      '',
      '    ∫u dv = uv − ∫v du',
      '',
      'Choose u using **LIATE** — Logarithmic, Inverse trig, Algebraic, Trig, Exponential.',
      'The function earlier in that list becomes u.',
      '',
      'Find ∫x·eˣ dx:',
      '',
      '1. u = x, so du = dx',
      '2. dv = eˣ dx, so v = eˣ',
      '3. ∫x·eˣ dx = x·eˣ − ∫eˣ dx = **x·eˣ − eˣ + c**',
      '',
      '## Definite integrals and area',
      '',
      '    ∫ from a to b of f(x) dx = F(b) − F(a)',
      '',
      'This gives the signed area between the curve and the x-axis.',
      '',
      '**Watch for sign.** Area below the x-axis comes out negative. If a question asks for the',
      'total area, split the integral at each x-intercept and add the absolute values.',
      '',
      '## Area between two curves',
      '',
      '    Area = ∫ from a to b of [f(x) − g(x)] dx',
      '',
      'where f(x) is the upper curve and g(x) the lower, and a and b are the intersection points.',
      '',
      '## Practise',
      '',
      '1. Find ∫(3x² + 4x − 5) dx.',
      '2. Use substitution to find ∫3x²(x³ + 2)⁴ dx.',
      '3. Evaluate ∫ from 0 to 2 of x² dx.',
    ].join('\n'),
  },

  {
    id: 'read-f6-eco-1-international-trade',
    topicId: 'f6-eco-1',
    title: 'International trade and comparative advantage',
    summary: 'Why countries trade, absolute versus comparative advantage, and the main trade barriers.',
    kind: 'lesson_note',
    readingMinutes: 10,
    sortOrder: 1,
    body: [
      '## Why countries trade',
      '',
      'No country can produce everything efficiently. Trade lets each country specialise where',
      'it is relatively better, then exchange — and both sides end up with more.',
      '',
      '## Absolute advantage',
      '',
      'A country has an **absolute advantage** if it can produce a good using fewer resources',
      'than another country.',
      '',
      '## Comparative advantage',
      '',
      'This is the real reason for trade, and it is subtler. A country has a **comparative',
      'advantage** in a good if it produces it at a **lower opportunity cost** than the other',
      'country — even if it is worse at everything.',
      '',
      '### Example',
      '',
      'Two countries, one day of labour:',
      '',
      '| | Cloth | Coffee |',
      '| --- | --- | --- |',
      '| Country A | 10 | 20 |',
      '| Country B | 6 | 4 |',
      '',
      'Country A is better at both — it has an absolute advantage in each.',
      '',
      'But look at opportunity cost:',
      '',
      '- A gives up 20 coffee to make 10 cloth → **2 coffee per cloth**',
      '- B gives up 4 coffee to make 6 cloth → **0.67 coffee per cloth**',
      '',
      'B has the lower opportunity cost in cloth, so B has a comparative advantage in cloth.',
      'A has a comparative advantage in coffee.',
      '',
      'Both gain if A specialises in coffee and B in cloth, then they trade.',
      '',
      '## Terms of trade',
      '',
      'The **terms of trade** is the ratio of export prices to import prices.',
      '',
      '    ToT = (index of export prices ÷ index of import prices) × 100',
      '',
      'A rise means a country gets more imports per unit of exports — favourable. A fall means',
      'the opposite.',
      '',
      '**This matters for Tanzania.** A country exporting raw commodities and importing',
      'manufactured goods can see its terms of trade worsen over time.',
      '',
      '## Barriers to trade',
      '',
      '- **Tariffs** — a tax on imports. Raises the domestic price, protects local producers,',
      '  but consumers pay more.',
      '- **Quotas** — a physical limit on how much can be imported.',
      '- **Subsidies** — government payments to domestic producers, making them cheaper.',
      '- **Embargoes** — a total ban on trade with a country.',
      '- **Non-tariff barriers** — standards, licensing and paperwork that slow imports.',
      '',
      '## Free trade areas',
      '',
      'Groups of countries reduce barriers among themselves. Examples include the EAC (East',
      'African Community), SADC and the African Continental Free Trade Area (AfCFTA).',
      '',
      '## Practise',
      '',
      '1. Distinguish absolute from comparative advantage.',
      '2. Using the table above, state each country\'s comparative advantage.',
      '3. Give two arguments for protecting domestic industry, and two against.',
    ].join('\n'),
  },
];

export async function seedReadings(queryable: AcademicQueryable): Promise<void> {
  for (const reading of READING_DATA) {
    await queryable.query(
      `INSERT INTO academic_readings
         (id, topic_id, title, summary, body, kind, source, reading_minutes, sort_order, published)
       VALUES ($1, $2, $3, $4, $5, $6, 'authored', $7, $8, TRUE)
       ON CONFLICT (id) DO NOTHING`,
      [
        reading.id,
        reading.topicId,
        reading.title,
        reading.summary,
        reading.body,
        reading.kind,
        reading.readingMinutes,
        reading.sortOrder,
      ],
    );
  }
}
